---
name: "Push Latest"

on:
  push:
    branches:
      - 'main'

jobs:
  build-push-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Build Arguments
        id: prepare_build_args
        run: |
          echo ::set-output name=build_created::$( date --utc +"%Y-%m-%dT%H:%M:%SZ" )
          echo ::set-output name=build_version::$( echo "latest" )
          echo ::set-output name=build_revision::$( echo "${{ github.sha }}" )

      - name: Set up QEMU
        id: setup_qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        id: ghcr_login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Containers to Registries
        id: build_publish
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jacobwoffenden/bin-day:${{ steps.prepare_build_args.outputs.build_version }}
          build-args: |
            BUILD_CREATED=${{ steps.prepare_build_args.outputs.build_created }}
            BUILD_VERSION=${{ steps.prepare_build_args.outputs.build_version }}
            BUILD_REVISION=${{ steps.prepare_build_args.outputs.build_revision }}
